esphome:
  name: esphome-1000
  friendly_name: ESPHome 1000

esp8266:
  board: d1_mini_lite

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-xxxxx"
    password: "xxx"

captive_portal:

output:
  - platform: esp8266_pwm
    pin: D1
    frequency: 1000 Hz
    id: esp_fans_1234

fan:
  - platform: speed
    output: esp_fans_1234
    name: "ESP Fans 1234"
